version: 2.0

jobs:
  build:
    docker:
      - image: docker:18.05.0-ce
    working_directory: /root/project/docker-development-environment
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -t $DOCKER_USER/development-tools-base:$CIRCLE_TAG Base

  deploy:
    docker:
      - image: docker:18.05.0-ce
    working_directory: /root/project/docker-development-environment
    steps:
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker push $DOCKER_USER/development-tools-base:$CIRCLE_TAG

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            ignore: /.*/
          tags:
            ignore: /^testing-.*/
      - deploy:
        requires:
          - build 
        filters:
          tags:
            only: /^v.*/       